import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/frame1000004509">Frame1000004509</Link>
        </li>
        <li>
          <Link to="/passwordresetenteremailtwo">
            PasswordresetenteremailTwo
          </Link>
        </li>
        <li>
          <Link to="/passwordresetenteremailfive">
            PasswordresetenteremailFive
          </Link>
        </li>
        <li>
          <Link to="/passwordresetenteremailten">
            PasswordresetenteremailTen
          </Link>
        </li>
        <li>
          <Link to="/passwordresetenteremailsix">
            PasswordresetenteremailSix
          </Link>
        </li>
        <li>
          <Link to="/passwordresetenteremaileleven">
            PasswordresetenteremailEleven
          </Link>
        </li>
        <li>
          <Link to="/passwordresetenteremailthree">
            PasswordresetenteremailThree
          </Link>
        </li>
        <li>
          <Link to="/register">Register</Link>
        </li>
        <li>
          <Link to="/registerfilledone">RegisterFilledOne</Link>
        </li>
        <li>
          <Link to="/registererrorone">RegisterErrorOne</Link>
        </li>
        <li>
          <Link to="/registerverifyemailone">RegisterVerifyEmailOne</Link>
        </li>
        <li>
          <Link to="/passwordresetentercode">Passwordresetentercode</Link>
        </li>
        <li>
          <Link to="/passwordresetentercodeone">PasswordresetentercodeOne</Link>
        </li>
        <li>
          <Link to="/frame1000004510">Frame1000004510</Link>
        </li>
        <li>
          <Link to="/passwordresetenteremailseven">
            PasswordresetenteremailSeven
          </Link>
        </li>
        <li>
          <Link to="/passwordresetenteremaileight">
            PasswordresetenteremailEight
          </Link>
        </li>
        <li>
          <Link to="/passwordresetenteremail">Passwordresetenteremail</Link>
        </li>
        <li>
          <Link to="/passwordresetenteremailnine">
            PasswordresetenteremailNine
          </Link>
        </li>
        <li>
          <Link to="/passwordresetenteremailone">
            PasswordresetenteremailOne
          </Link>
        </li>
        <li>
          <Link to="/passwordresetenteremailfour">
            PasswordresetenteremailFour
          </Link>
        </li>
        <li>
          <Link to="/registerone">RegisterOne</Link>
        </li>
        <li>
          <Link to="/registerfilled">RegisterFilled</Link>
        </li>
        <li>
          <Link to="/registererror">RegisterError</Link>
        </li>
        <li>
          <Link to="/registerverifyemail">RegisterVerifyEmail</Link>
        </li>
        <li>
          <Link to="/passwordresetentercodetwo">PasswordresetentercodeTwo</Link>
        </li>
        <li>
          <Link to="/passwordresetentercodethree">
            PasswordresetentercodeThree
          </Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
